### ISSUE TITLE
Potential breaking changes for the NNBD release

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/async#109] opened 2020-03-17 19:03 UTC
Below is a list of potential changes we might wish to make when we do the NNBD migration, either to help having fewer nullable types in our apis or generally take advantage of a breaking release to improve other apis:

- [ ] Result.asValue/Result.asError should throw instead of returning null
- [ ] CancelableOperation.valueOrCancellation should have a required param of type T

Feel free to edit this comment and add your own suggestions.

**Comment by lrhn** [comment] 2020-06-10 10:02
I'd probably keep `asValue`/`asResult` as nullable. Using `asX` to return `X` or null is common usage. 
Otherwise, you'd need to first check if it's a value before calling `asValue`, and that'll cause two checks.

If you want to get a value or throw, you can use `as ResultValue` directly.

**Comment by natebosch** [comment] 2020-06-16 23:03
`ResultValue` is not in the public API.

`null` is a valid value for a `Result<String?>`. I think throwing for a non-value result is the most clear approach.

**Comment by lrhn** [comment] 2020-06-17 08:36
My bad, I meant `ValueResult` (which reads better, but is less discoverable).
It's the return type of `asResult`, so it is public.

The *purpose* of `asResult` is to *both* test and cast, like the `as` operation in C#. It should work on `ErrorResult` objects as well, and return `null` for them. 
If you just want to throw for non-values, `as ValueResult` does that, so there is no need for a member doing it too.

So, by design, the return type of `asResult` should be `ValueResult<T>?`. 
It does not return the actual *value*, so whether `null` is a valid value for `Result<String?>` doesn't matter (the API is designed so that it doesn't matter).
Returning the value is unsafe to do that before actually checking that it's not an error.

(`CancelableIOperation` might need changes. The "optional result value" occurs in many places, and we either change the API to make it required, or make it throw when omitted and the type is non-nullable, because that's backwards compatible).

**Comment by natebosch** [comment] 2020-11-06 17:31
I took a look at `CancelableOperation.valueOrCancellation` and I'm leaning away from making any changes. From what I can tell the usage is vastly skewed towards not caring about the specific value, most usages omit the argument and a bunch even pass `null` specifically. Many usages either treated the result as a `Future<void>` instead of `Future<T>`, or only called `whenComplete` instead of `then`.

I'm in favor of closing this, I don't recall any other null safety specific changes I had wanted to make.

**Closed** 2020-11-06 18:17 UTC
Labels: next-breaking-release
